version: "2"

services:

  webserver:
    build:
      context: ./docker
    image: docker-socket-core
    volumes:
      - ./build/libs:/app
    ports:
      - "8080:8080"
      - "8000:8000"
    restart: always
